name: anubis-anti-scraper
summary: Stop incoming HTTP requests from AI crawlers using proof-of-work.
description: |
  Anubis weighs the soul of your connection using a sha256 proof-of-work challenge in order to protect upstream resources from scraper bots.

adopt-info: anubis

version: "1.19.0-pre1"

base: core24

platforms:
  amd64:
  arm64:
  riscv64:

confinement: strict

grade: stable

issues: https://github.com/lgp171188/anubis-snap/issues

license: MIT

apps:
  anubis-anti-scraper:
    command: usr/bin/anubis
    plugs:
      # Some options require being able to read/write files. So this provides
      # a limited way for that.
      - home
      - network-bind

parts:
  anubis:
    plugin: dump
    # There is no riscv64 snap for node or an official distribution from
    # upstream. So we install the npm package from the Ubuntu archive for
    # riscv64 and on the other supported architectures, we install the node
    # snap.
    build-packages:
      - to riscv64:
          - brotli
          - esbuild
          - gzip
          - npm
          - zstd
      - else:
          - brotli
          - esbuild
          - gzip
          - zstd
    build-snaps:
      - to riscv64:
          - go/latest/stable
      - else:
          - go/latest/stable
          - node/22/stable
    source: https://github.com/TecharoHQ/anubis.git
    source-type: git
    source-tag: "v$SNAPCRAFT_PROJECT_VERSION"
    source-depth: 1
    build-environment:
      - PATH: ${CRAFT_PART_BUILD}/node_modules/.bin:${PATH}
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --exact-match --tags --match=v*.*.* | sed 's/v//')"
    override-build: |
      make deps
      make assets
      make build
      install -Dm755 ${CRAFT_PART_BUILD}/var/anubis ${CRAFT_PART_INSTALL}/usr/bin/anubis
      install -Dm644 ${CRAFT_PART_BUILD}/run/default.env ${CRAFT_PART_INSTALL}/etc/anubis/default.env
      install -Dm644 ${CRAFT_PART_BUILD}/run/anubis@.service ${CRAFT_PART_INSTALL}/usr/lib/systemd/system/anubis@.service
      install -Dm644 ${CRAFT_PART_BUILD}/data/botPolicies.json ${CRAFT_PART_INSTALL}/usr/share/doc/anubis/botPolicies.json
      install -Dm644 ${CRAFT_PART_BUILD}/data/botPolicies.yaml ${CRAFT_PART_INSTALL}/usr/share/doc/anubis/botPolicies.yaml
      install -Dm644 ${CRAFT_PART_BUILD}/LICENSE ${CRAFT_PART_INSTALL}/usr/share/licenses/anubis/LICENSE
